apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubehunter
  labels:
       marc2: kubehunter
spec:
  selector:
     matchLabels:
       marc2: kubehunter
  template:
    metadata:
      labels:
        marc2: kubehunter
    spec:
      nodeSelector:
        marc2: kubehunternode
      containers:
        - name: kubehunter
          image: aquasec/kube-hunter
          securityContext:
             allowPrivilegeEscalation: true
             privileged: true
          command:
          - bin/sleep
          - infinity
      serviceAccount: samarc
      serviceAccountName: samarc
